<a href="https://colab.research.google.com/github/lohaarja/MLVault/blob/main/Medicine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv(r"/content/Training.csv")
data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


In [4]:
x=data.drop('prognosis',axis='columns')
y=data['prognosis']

In [5]:
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=20)

In [7]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

In [8]:
import numpy as np

In [9]:
model={
    "SVC":SVC(kernel="linear"),
    "RandomForestClassifier":RandomForestClassifier(n_estimators=100,random_state=42),
    "KNeighborsClassifier":KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB":MultinomialNB(),
    "GradientBoostingClassifier":GradientBoostingClassifier(n_estimators=100,random_state=42),
}
for model_name,models in model.items():
  models.fit(x_train,y_train)
  y_pred=models.predict(x_test)
  print(y_pred)
  print(model_name,accuracy_score(y_test,y_pred))


[40  6 16 ...  8 10 33]
SVC 1.0
[40  6 16 ...  8 10 33]
RandomForestClassifier 1.0
[40  6 16 ...  8 10 33]
KNeighborsClassifier 1.0
[40  6 16 ...  8 10 33]
MultinomialNB 1.0
[40  6 16 ...  8 10 33]
GradientBoostingClassifier 1.0


In [10]:
svc=SVC(kernel="linear")
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
print(accuracy_score(y_test,y_pred))

1.0


In [11]:
import pickle
filename='medicine_svc.sav'
pickle.dump(svc,open(filename,'wb'))
loaded_svc=pickle.load(open(filename,'rb'))
print("Predicted disease:",loaded_svc.predict(x_test.iloc[0].values.reshape(1,-1)))
print("Actual disease:",y_test[0])

Predicted disease: [40]
Actual disease: 40


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [12]:
symptoms=pd.read_csv(r"/content/symtoms_df.csv")
precautions=pd.read_csv(r"/content/precautions_df.csv")
description=pd.read_csv(r"/content/description.csv")
workout=pd.read_csv(r"/content/workout_df.csv")
diet=pd.read_csv(r"/content/diets.csv")
medications=pd.read_csv(r"/content/medications.csv")


In [47]:
def fc(predicted,workout):
    desc = description[description['Disease'] == predicted]['Description']
    desc = " ".join([w for w in desc])

    pc = precautions[precautions['Disease'] == predicted][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pc = [col for col in pc.values]

    med = medications[medications['Disease'] == predicted]['Medication']
    med = [med for med in med.values]

    diets = diet[diet['Disease'] == predicted]['Diet']
    diets = [diets for diets in diets.values]

    workout = workout[workout['disease'] == predicted] ['workout']


    return desc,pc,med,diets,workout

In [48]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

In [49]:
def get_predicted_value(patient_data):
  array=np.zeros(len(symptoms_dict))
  for item in patient_data:
    array[symptoms_dict[item]]=1
  return diseases_list[loaded_svc.predict([array])[0]]

In [54]:
symp = input("Enter symptoms (comma-separated without spaces): \n itching\n	skin_rash\n	nodal_skin_eruptions\n	continuous_sneezing\n	shivering\n	chills\n	joint_pain\n	stomach_pain\n	acidity\n	ulcers_on_tongue\n	...	\nblackheads\n	scurring\n	skin_peeling\n	silver_like_dusting\n	small_dents_in_nails\n	inflammatory_nails\n	blister\n	red_sore_around_nose\n	yellow_crust_ooze\n ")
patient_symp = [s.strip() for s in symp.split(',')]
patient_symp = [symp.strip("[]' ") for symp in patient_symp]

predicted_disease = get_predicted_value(patient_symp)
desc, pc, med, diets, workout_data = fc(predicted_disease, workout)

print("Predicted disease:\n", predicted_disease,'\n')
print("Description:\n", desc,'\n')
print("Precautions:\n", pc,'\n')
print("Medication:\n", med,'\n')
print("Diet:\n", diets,'\n')
print("Workout:\n", workout_data,'\n')

Enter symptoms (comma-separated without spaces): 
 itching
	skin_rash
	nodal_skin_eruptions
	continuous_sneezing
	shivering
	chills
	joint_pain
	stomach_pain
	acidity
	ulcers_on_tongue
	...	
blackheads
	scurring
	skin_peeling
	silver_like_dusting
	small_dents_in_nails
	inflammatory_nails
	blister
	red_sore_around_nose
	yellow_crust_ooze
 blackheads
Predicted disease:
 Acne 

Description:
 Acne is a skin condition that occurs when hair follicles become clogged with oil and dead skin cells. 

Precautions:
 [array(['bath twice', 'avoid fatty spicy food', 'drink plenty of water',
       'avoid too many products'], dtype=object)] 

Medication:
 ["['Antibiotics', 'Pain relievers', 'Antihistamines', 'Corticosteroids', 'Topical treatments']"] 

Diet:
 ["['Acne Diet', 'Low-Glycemic Diet', 'Hydration', 'Fruits and vegetables', 'Probiotics']"] 

Workout:
 370                Consume a balanced diet
371    Limit dairy and high-glycemic foods
372                   Include antioxidants
373           

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
